/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moviemaster;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import jess.*;
import jess.awt.TextAreaWriter;
/**
 *
 * @author hatem
 */
public class MovieFinder extends javax.swing.JFrame {

    /**
     * Creates new form MovieFinder
     */
    public MovieFinder() {
        initComponents();
        resultat.setText("fff");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox1.setName("acteur"); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 40, 108, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox2.setName("genre"); // NOI18N
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(431, 38, 135, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox3.setName("contenu"); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(160, 130, 108, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox4.setName("annee"); // NOI18N
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(440, 130, 135, 20);

        jLabel1.setText("Acteur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 32, 14);

        jLabel2.setText("Genre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 40, 60, 20);

        jLabel3.setText("Contenu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 41, 14);

        jLabel4.setText("Anneé");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 130, 60, 20);

        jLabel5.setText("Nom de Film :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 330, 90, 14);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox5.setName("pays"); // NOI18N
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(160, 210, 110, 20);

        jLabel6.setText("Pays");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 214, 60, 20);

        jLabel7.setText("Producteur");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 210, 60, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        jComboBox6.setName("producteur"); // NOI18N
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(440, 210, 140, 20);

        jButton1.setText("Chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 290, 100, 23);

        resultat.setColumns(20);
        resultat.setRows(5);
        jScrollPane1.setViewportView(resultat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 330, 166, 96);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Film f= new Film();
            f.setActeur("a");
            f.setAnnee("a");
            f.setContenu("a");
            f.setGenre("a");
            f.setPays("a");
            f.setProducteur("a");
            Rete engine = new Rete();
            
            engine.batch("movie.clp");
            engine.add(f);
            
            
            
          
            engine.run();
            resultat.setText(f.getNom());
            
        } catch (JessException ex) {
            Logger.getLogger(MovieFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieFinder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultat;
    // End of variables declaration//GEN-END:variables
}
